knpu_oauth2_client:
    http_client_options:
        # THIS IS VERY INSECURE!
        verify: false

    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        e4o:
            type:           generic
            provider_class: App\OAuth\Provider\E4oProvider
            redirect_route: oauth_redirect_uri

            client_id:     '%oauth.client_id%'
            client_secret: '%oauth.client_secret%'

            provider_options:
                serverUrl:           '%oauth.server.url%'
                serverAuthorizePath: '%oauth.server.authorize_path%'
                serverTokenPath:     '%oauth.server.token_path%'
                serverProfilePath:   '%oauth.server.profile_path%'
